### ISSUE TITLE
不兼容高版本idea

### ISSUE THREAD

**Issue by isslin** [newhoo/RestfulBox-Solon#1]
![image](https://github.com/newhoo/RestfulBox-Solon/assets/55171079/23ef5cdc-4fbe-4ef7-9d60-851997aad2a3)

**Comment by newhoo** [comment]
插件还在审核中，可先本地方式安装。先在线安装RestfulBox插件，再本地安装solon，参考README

**Comment by newhoo** [comment]
已发布，请移步仓库下载
