### ISSUE TITLE
Solon单体项目只显示部分URL

### ISSUE THREAD

**Issue by isslin** [newhoo/RestfulBox-Solon#2]
![31de9124d8aedb30e136a1b73958485](https://github.com/newhoo/RestfulBox-Solon/assets/55171079/0ed9320a-0d5c-463c-a69e-6063ad0151ed)
只能显示部分URL，其他接口也有是开放了（登录）

**Comment by isslin** [comment]
![image](https://github.com/newhoo/RestfulBox-Solon/assets/55171079/932f937f-b495-4188-aa4c-0d5bc40e9a5e)
搜索功能也是只能搜索显示出来的部分URL

**Comment by isslin** [comment]
version
RestfulSolon: 1.0.1
idea: 2024.1

**Comment by newhoo** [comment]
你照着其他显示的类对比下吧，尤其是注解，插件识别不一定全面，核心识别逻辑看这里：https://github.com/newhoo/RestfulBox-Solon/blob/main/src/main/java/io/github/newhoo/restkit/ext/solon/language/JavaLanguageResolver.java#L50

建议你在本地拉插件代码调试下，本人目前没精力维护这个solon识别，而且我也不用solon
